Repository opensergo/opensergo-control-plane, pull requests merged in 2022-12, with the labels that each got.

#34 add skip-dirs in golangci-lint
  .github/workflows/go.yaml
Labels: area/ci

#32 Add support for traffic-routing spec v1alpha1
  .gitignore
  config/crd/bases/traffic.opensergo.io_trafficerouters.yaml
  config/samples/opensergo_traffic_router_samples.yaml
  control_plane.go
  go.mod
  go.sum
  pkg/api/v1alpha1/traffic/groupversion_info.go
  pkg/api/v1alpha1/traffic/traffic_router.go
  pkg/api/v1alpha1/traffic/traffic_router.pb.go
  pkg/api/v1alpha1/traffic/traffic_router_deepcopy.pb.go
  pkg/api/v1alpha1/traffic/zz_generated.deepcopy.go
  pkg/controller/crd_meta.go
  pkg/controller/crd_watcher.go
  pkg/controller/k8s_operator.go
  pkg/controller/traffic_router_transform.go
  pkg/proto/router/v1/route_fallback.pb.go
  pkg/proto/router/v1/route_fallback.proto
  pkg/proto/validate/v1/validate.pb.go
  pkg/proto/validate/v1/validate.proto
  pkg/util/util.go
Labels: kind/feature

#36 Fix bad-param of hasSubscribed judge for CRDWatcher
  pkg/controller/crd_watcher.go
  pkg/model/subscribe.go
Labels: kind/bugfix
