Repository opensergo/opensergo-control-plane, pull requests merged in 2023-01, with the labels that each got.

#42 Split CI workflow into two parts and use golangci-lint-action as linter
  .github/workflows/ci.yml
  .github/workflows/go.yaml
  .golangci.yml
Labels: area/ci

#41 Add the k8s related crd configuration of the opensergo-control-plane
  config/rbac/role.yaml
  k8s/crd/bases/fault-tolerance.opensergo.io_circuitbreakerstrategies.yaml
  k8s/crd/bases/fault-tolerance.opensergo.io_concurrencylimitstrategies.yaml
  k8s/crd/bases/fault-tolerance.opensergo.io_faulttolerancerules.yaml
  k8s/crd/bases/fault-tolerance.opensergo.io_ratelimitstrategies.yaml
  k8s/crd/bases/fault-tolerance.opensergo.io_throttlingstrategies.yaml
  k8s/crd/bases/traffic.opensergo.io_trafficerouters.yaml
  k8s/opensergo-control-plane.yaml
  k8s/rbac/rbac.yaml
  samples/opensergo_new_sample.yaml
  samples/opensergo_traffic_router_samples.yaml
Labels: area/build-release

#44 Update init.sh
  cmd/install/init.sh
Labels: kind/bug

#45 Optimize cmd directory structure
  README.md
  cmd/init/init.sh
  cmd/install/k8s/deploy.sh
  k8s/workload/opensergo-control-plane.yaml
Labels: area/build-release
